sudo: required
services:
    - docker

before_install:
    - docker build -t asnaebeya/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true asnaebeya/react-test npm test

after_success:
    - docker build -t asnaebeya/multi-client ./client
    - docker build -t asnaebeya/multi-nginx ./nginx
    - docker build -t asnaebeya/multi-server ./server
    - docker build -t asnaebeya/multi-worker ./worker
    # login
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push to docker hub
    - docker push asnaebeya/multi-client
    - docker push asnaebeya/multi-nginx
    - docker push asnaebeya/multi-server
    - docker push asnaebeya/multi-worker
#add travis
